name: Performance

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    name: 📈 Benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.12"
          architecture: x64

      - name: Install with poetry
        run: |
          pipx install poetry
          poetry env use 3.12
          poetry install --with test

      - name: Run benchmarks with CodSpeed
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: poetry run pytest tests --benchmark-enable --codspeed
